In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pylab import mpl
# 设置显示中文字体
mpl.rcParams["font.sans-serif"] = ["SimHei"]
# 设置正常显示符号
mpl.rcParams["axes.unicode_minus"] = False

In [2]:
data = pd.read_csv('./Data/kj1688.csv')

In [3]:
data.head()

,商品id,标题,价格,计量单位,销量,大类,小类,封面图,生产商,商品链接,商家店铺链接
0,544683494743,1010系列经典款 不锈钢餐具牛排刀叉勺调羹 酒店西餐餐具促销礼品,1.17,支,74249,餐具,西餐餐具,http://cbu01.alicdn.com/img/ibank/2019/878/440...,揭阳市榕城区佳佰利不锈钢制品厂,https://detail.1688.com/offer/544683494743.htm...,https://shop1483807565292.1688.com
1,524607110046,日式环保缠线勺叉筷子三件套 创意成人长柄木质椭圆餐具套装批发,3.15,套,24294,餐具,西餐餐具,http://cbu01.alicdn.com/img/ibank/2015/006/342...,福建省莆田万森家居用品有限公司,https://detail.1688.com/offer/524607110046.htm...,https://shop1444725876497.1688.com
2,560718614791,304不锈钢葡萄牙餐具刀叉勺套装北欧西餐黑金牛排刀叉勺子,3.50,套,41643,餐具,西餐餐具,http://cbu01.alicdn.com/img/ibank/2019/942/123...,揭阳市榕城区榕东明兴不锈钢制品厂,https://detail.1688.com/offer/560718614791.htm...,https://jymingxing3.1688.com
3,537030324952,不锈钢尖尾水果叉小勺子 甜品叉 不锈钢小叉子 勺子 餐具直销赠品,0.11,支,42663,餐具,西餐餐具,http://cbu01.alicdn.com/img/ibank/2017/695/496...,义乌市超奇日用百货有限公司,https://detail.1688.com/offer/537030324952.htm...,https://zjywzzj.1688.com
4,563957457641,不锈钢卡通勺子 儿童可爱叉勺 西餐幼儿园勺叉子,2.30,支,716,餐具,西餐餐具,http://cbu01.alicdn.com/img/ibank/2018/562/972...,义乌市虎踞日用百货有限公司,https://detail.1688.com/offer/563957457641.htm...,https://shop1406652927465.1688.com

In [7]:
data.groupby(by='大类')['销量','价格'].describe()

          销量                                                                 \
       count         mean            std  min  25%   50%     75%        max
大类
厨房工具  5699.0  4258.589402  105704.018307  0.0  0.0   5.0  294.00  7870966.0
厨房整理  2689.0  1611.210859   15049.261843  0.0  0.0   3.0  170.00   592761.0
厨用刀剪  1287.0  2322.270396   18766.528371  0.0  0.0   0.0  106.50   407576.0
烘焙用品  1596.0  3993.614035   26301.366721  0.0  0.0  19.5  679.75   837960.0
烧烤用具  1142.0  1604.796848   15404.575204  0.0  0.0   0.0   20.00   371687.0
酒具    1331.0  1321.021037    8524.159095  0.0  0.0   0.0   57.50   195930.0
锅/煲   2324.0   413.996127    2725.022044  0.0  0.0   0.0   20.00    68616.0
餐具    4652.0  8725.714531  126235.241626  0.0  0.0  24.0  651.50  7277874.0

          价格
       count        mean          std   min   25%    50%   75%       max
大类
厨房工具  5699.0   20.968826   528.922382  0.00   1.9   4.60  10.0  38000.00
厨房整理  2689.0   16.685366    37.374268  0.00   2.6   6.57  16.8    880.00
厨用刀剪  1287.0   12.752828    28.344746  0.05   3.0   6.00  12.0    430.82
烘焙用品  1596.0   14.492462    91.578320  0.00   2.2   5.30  11.5   2800.00
烧烤用具  1142.0   81.747329   342.875542  0.00   3.0  10.43  38.0   4880.00
酒具    1331.0   28.079977    71.745660  0.00   3.0   8.00  23.4   1508.00
锅/煲   2324.0  135.338550  2307.188374  0.00  18.0  36.50  78.0  99999.00
餐具    4652.0   18.835918    98.110932  0.00   1.9   4.80  12.0   5000.00

In [11]:
data.groupby(by='大类')['销量'].mean()

大类
厨房工具    4258.589402
厨房整理    1611.210859
厨用刀剪    2322.270396
烘焙用品    3993.614035
烧烤用具    1604.796848
酒具      1321.021037
锅/煲      413.996127
餐具      8725.714531
Name: 销量, dtype: float64

In [20]:
data.groupby(by='大类')['价格'].std()

大类
厨房工具     528.922382
厨房整理      37.374268
厨用刀剪      28.344746
烘焙用品      91.578320
烧烤用具     342.875542
酒具        71.745660
锅/煲     2307.188374
餐具        98.110932
Name: 价格, dtype: float64

In [22]:
data.groupby(by='大类').sort_values(by=['价格'], ascending=False)

AttributeError: Cannot access callable attribute 'sort_values' of 'DataFrameGroupBy' objects, try using the 'apply' method